"use strict";
const newList = ['Amreen', 'Ahmed', 'Azfer', 'Aslam', 'Nouman', 'Saleem'];
console.log('we could not find a bigger table to adjust all');
//we will shrink the List
console.log(`sorry ${newList[5]},we could not a find a bigger table for the dinner`);
newList.pop();
console.log(newList);
console.log(`sorry ${newList[4]},we could not a find a bigger table for the dinner`);
newList.pop();
console.log(newList);
console.log(`sorry ${newList[3]},we could not a find a bigger table for the dinner`);
newList.pop();
console.log(newList);
console.log(`sorry ${newList[2]},we could not a find a bigger table for the dinner`);
newList.pop();
console.log(newList);
console.log(`Dear ${newList[0]},You are still invited for the dinner`);
console.log(`Dear ${newList[1]},You are still invited for the dinner`);
newList.splice(0, 2);
console.log(newList);
