"use strict";
let city_islambad = 'capitalPak';
let city_dehli = 'capitalindia';
let city_bejing = 'capitalchina';
let my_Freinds = ['amin', 'abdul', 'zubair'];
console.log("city_islambad== capitalindia ? i predict false");
console.log(city_islambad = "capitalindia");
console.log("city_bejing == capitalchina? i predict true");
console.log(city_bejing == 'capitalchina');
console.log('city_islambad===capitalPak && city_dehli===capitalchina? I predict false');
console.log(city_islambad === 'capitalPak' && city_dehli === 'capitalchina');
console.log("city_bejing ==='capitalchina' || city_dehli ==='capitalPak' i predict true");
console.log(city_bejing === 'capitalchina' || city_dehli === 'capitalPak');
console.log('my_Freinds.includes("amin" i predict true)');
console.log(my_Freinds.includes('amin'));
console.log("my_Freinds.includes('azfer')i predict false");
console.log(my_Freinds.includes('azfer'));
